Feature/add participants
zagrajmy/backend pull request #85
Opened 2020-08-23 21:31 UTC by lprasol

2020-08-29 19:24 UTC, radowit commented
What I did to fix Hasura:
- removed nb_meeting_participants from all migrations and metadata (and removed migrations that contained only this)
- restarted docker
- re-added meeting participant table and relationships

2020-10-04 05:56 UTC, radowit requested changes

2020-10-04 05:56 UTC, radowit commented on app/notice_board/views.py
> +        meeting.participants.remove(request.user)
Atfer you remove a participant you need to check i there is anyone that can pop in for his place.
You could reuse code from add participant action.

2020-10-04 06:04 UTC, radowit commented on app/notice_board/views.py
> +                participant.status = MeetingParticipant.CONFIRMED
This branch is not covered in unit tests

2020-10-11 13:28 UTC, radowit approved these changes

2020-10-11 13:58 UTC, merged

2020-10-13 19:34 UTC, lprasol commented
![](https://github.trello.services/images/mini-trello-icon.png) [Zapisywanie się na sesje](https://trello.com/c/QUxSZ942/39-zapisywanie-si%C4%99-na-sesje)